# Generated by Django 4.2.2 on 2023-07-01 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company_type', models.CharField(choices=[('FA', 'Factory'), ('DB', 'Distributor'), ('DS', 'Dealership'), ('RT', 'Retail'), ('IE', 'Individual')], max_length=50)),
                ('debt_to_supplier', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
        ),
    ]
