# Generated by Django 4.2.2 on 2023-07-01 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='create_date',
        ),
        migrations.AddField(
            model_name='company',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
