# Generated by Django 4.2.2 on 2023-07-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_create_date_company_creation_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(check=models.Q(('debt_to_supplier__gte', 0)), name='positive_debt', violation_error_message='Debt must be positive'),
        ),
    ]
