# Generated by Django 4.2.3 on 2023-07-05 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_company_employees_company_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='level',
        ),
    ]
